name: main workflow

on: pull_request_target


jobs:
  featuer:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: featuer type
        run: |
          title="${{ github.event.pull_request.title }}"
          if [[ $title =~ ^feat ]]; then
            echo "Feature change"
          fi
        