name: main workflow

on: pull_request


jobs:
  featuer:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: featuer type
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        run: |
          bash test.sh
          
          title="${{ github.event.pull_request.title }}"
          if [[ $title =~ ^feat ]]; then
            echo "Feature change"
          fi
        
